[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
description = "Poiesis (TES) MCP server"
name = "poiesis-mcp"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"
